// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace GameStateTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State_Carousel)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State_NonCombat)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State_Combat)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State_Combat_Preparation)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State_Combat_Active)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State_Combat_Result)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Game_State_Combat_End)
}

namespace UnitGameplayTags
{
	// ==== Unit Types ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Sparrow)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Raven) // Paragon Sparrow
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Drongo)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_AlienInvader) // Paragon Drongo
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Greystone)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Yin)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Phase)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Kitty) // Paragon Phase
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Gideon)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Mephisto) // Paragon Gideon
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Undertow) // Paragon Gideon
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Wukong)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_FutureKing) // Paragon Wukong
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Infernal) // Paragon Wukong
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Terra)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Shogun) // Paragon Murdock
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_MatteBlack) // Paragon Murdock
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Twinblast)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_ShadowOps) // Paragon Twinblast
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Revenant)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Zinx)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_GRIMexe)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_IggyScorch)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Gadget)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Shinbi)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Muriel)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_FengMao)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Khaimera)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Bengal)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Kwang)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_ZombieKwang)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Serath)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Sevarog)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Aurora)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_UndeadQueen)	// Paragon Aurora
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Countess)	// Paragon Countess
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Serika)	// Paragon Countess
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Kallari)	// Paragon Kallari
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Riktor)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Sektor)	// Paragon Riktor
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Steel)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Rampage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Narbash)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Hero_Boris)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Creep)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Creep_MinionLv1)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Creep_Melee)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Type_Creep_Range)

	// ==== Unit Attack Types ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_AttackType_Basic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_AttackType_Ultimate)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_AttackType_BonusDamage)
	
	// ==== Unit Damage Types ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageType_Physical)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageType_Magic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageType_TrueDamage)

	// ==== Unit Attack Flags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageFlag_NoCrit)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageFlag_NoVamp)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageFlag_NoManaGain)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageFlag_NoSendDamageAppliedEvent)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_DamageFlag_NoSendHitEvent)

	// ==== Unit Combat Text Type Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_CombatText_Type)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_CombatText_Type_Damage_Physical)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_CombatText_Type_Damage_Magic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_CombatText_Type_Damage_TrueDamage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_CombatText_Type_Heal)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_CombatText_Type_Miss)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_CombatText_Flag_Critical)
	
	// ==== Unit Ability Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_MontagePlay)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Attack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Attack_Basic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Attack_Ultimate)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Movement_Jump)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_PeriodPulse)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_ManaRegen)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Cyborg)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Guardian)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Undead)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Demon)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Imperial)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Beast)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_BladeMaster)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Mechanic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Synergy_Marksman)

	// ==== Unit State Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Combat_Alive)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Combat_Dead)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Combat_Attacking)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Combat_Stun)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Combat_Jumping)

	// ==== Unit Cooldown Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Cooldown_BasicAttack)
	
	// ==== Unit Anim Montage Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Montage_LevelStart)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Montage_Attack_Basic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Montage_Attack_Ultimate)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Montage_Death)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Montage_Combat_Win)

	// ==== Unit GameplayEvent Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_SpawnProjectileSucceed)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_AttackSucceed)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_HitSucceed)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_HitSucceed_Basic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_HitSucceed_Ultimate)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_HitSucceed_BonusDamage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_DamageApplied)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_OnHit)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_Combat_Win)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_Combat_End)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Event_Jump_Start)

	// ==== Unit Buff Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Buff_Synergy_Darkness_TrueDamage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Buff_Synergy_Mage_DoubleManaGain)
}

namespace SynergyGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Human)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Demon)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Imperial)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Robot)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Cyborg)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Beast)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Undead)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Species_Darkness)

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_Marksman)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_Mechanic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_BladeMaster)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_Knight)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_Mage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_Guardian)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_Assassin)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Synergy_Job_Bruiser)
}

namespace GameplayEffectTags
{
	// ==== Instant GE ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_ManaChange)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_Damage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_Heal)

	// ==== Infinite GE ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_MaxHealth)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_CombatStartMana)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_ManaRegen)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_BaseDamage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_PhysicalDamageMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_MagicDamageMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_DamageMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_AttackRange)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_AttackSpeedIncreaseMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_AttackSpeedDecreaseMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_PhysicalDefense)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_MagicDefense)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_CritChance)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_CritMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_LifeSteal)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_FlatDamageBlock)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Infinite_EvasionChance)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_GrantTag_Infinite)
	
	// ==== Duration GE ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Cooldown_BasicAttack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_GrantTag_Duration)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Class_Unit_AttributeChange_Add_Duration_AttackSpeedIncreaseMultiplier)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Damage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Heal)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_CurrentHealth)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_MaxHealth)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_CurrentMana)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_MaxMana)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_CombatStartMana)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_ManaRegen)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_BaseDamage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_PhysicalDamageMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_MagicDamageMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_DamageMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_AttackRange)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_AttackSpeed)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_AttackSpeedIncreaseMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_AttackSpeedDecreaseMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_PhysicalDefense)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_MagicDefense)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_CritChance)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_CritMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_LifeSteal)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_FlatDamageBlock)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Stat_EvasionChance)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Cooldown_BasicAttack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Caller_Duration)
}

namespace GameplayCueTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_LevelUp)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Combine)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_EquipItem)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_SynergyActive)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_PlayEffectAtSocket)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_SFX_Unit_AttackSound)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_SFX_Unit_LevelStart)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_UI_Unit_CombatText)

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_LevelUp)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_BuyXP)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_BuyUnit)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_SellUnit)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_ShopRefresh)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_ItemCapsuleOpen)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_Attack)
}

namespace PlayerGameplayTags
{
	// ==== Player Type Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Type_LittleDragon)
	
	// ==== Player Stat Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Stat_PlayerLevel)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Stat_PlayerXP)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Stat_PlayerGold)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Stat_PlayerHP)

	// ==== Player State Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Normal)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Carousel)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Dead)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_MaxLevel)
	
	// ==== Player Shop Ability Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_GA_Shop_BuyXP)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_GA_Shop_BuyUnit)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_GA_Shop_SellUnit)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_GA_Shop_ShopRefresh)

	// ==== Player Action Ability Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Action_Attack_Basic)
	
	// ==== Player Event Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Damage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ProjectileHit)
}

namespace GameRoundTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_Start)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_SetUp)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_PvP)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_PvE)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_PvE_MinionsLv1)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_PvE_MinionsLv2)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_PvE_MinionsLv3)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_PvE_MinionsLv4)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameRound_Carousel)
}

namespace ItemTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item)
	
	// ==== Base Item Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_BFSword)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_ChainVest)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_GiantsBelt)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_LargeRod)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_NegatronCloak)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_RecurveBow)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_SparringGloves)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_TearofGoddess)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_Spatula)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Base_FryingPan)

	// ==== Advanced Item Tags ====
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_BloodThirster)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_BrambleVest)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_CrownGuard)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_DeathBlade)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_DeathCap)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_DragonsClaw)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_EdgeofNight)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_EvenShroud)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_GargoyleStoneplate)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_GiantSlayer)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_GuinsoosRageblade)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_HextechGunblade)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_InfinityEdge)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_IonicSpark)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_JeweledGauntlet)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_KrakensFury)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_LastWhisper)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_Morellonomicon)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_NashorsTooth)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_QuickSilver)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_RedBuff)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_SteadfastHeart)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_SteraksGage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_StrikersFrail)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_SunfireCape)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_ThiefsGloves)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_TitansResolve)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_WarmogsArmor)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_SpearofShojin)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_ProtectorsVow)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_SpiritVisage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_ArchangelsStaff)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_AdaptiveHelm)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_VoidStaff)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_HandofJustice)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_BlueBuff)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_TacticiansCrown)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_TacticiansCape)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Advanced_TacticiansShield)

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_BladeMaster)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Guardian)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Bruiser)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Mage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Knight)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Marksman)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Assassin)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Mechanic)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Undead)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Imperial)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Cyborg)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Darkness)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Human)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Beast)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Robot)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Symbol_Demon)
}
